APPLICATION = malila
BOARD ?= pinetime
RIOTBASE ?= riot

PROGRAMMER ?= openocd
OPENOCD_DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 2

USEMODULE += xtimer
USEMODULE += ili9341
USEMODULE += cst816s

include $(RIOTBASE)/Makefile.include
