WERROR=0
APPLICATION = malila
RIOTBASE ?= riot

# Add modules folder to compile custom modules
EXTERNAL_MODULE_DIRS += modules

# Modules including custom ones
USEMODULE += xtimer
USEMODULE += common
USEMODULE += graphics

include $(RIOTBASE)/Makefile.include