APPLICATION = malila
BOARD ?= pinetime
RIOTBASE ?= riot

# Packages
#USEPKG += micropython

# Add modules folder to compile custom modules
EXTERNAL_MODULE_DIRS += modules/display
EXTERNAL_MODULE_DIRS += modules/gui

# Custom modules
USEMODULE += display
USEMODULE += gui

include $(RIOTBASE)/Makefile.include
